#pragma once

#include <Arduino.h>

#ifndef TINYMESH_SCK_PIN
#define TINYMESH_SCK_PIN     4
#endif

#ifndef TINYMESH_MISO_PIN
#define TINYMESH_MISO_PIN    6
#endif

#ifndef TINYMESH_MOSI_PIN
#define TINYMESH_MOSI_PIN    5
#endif

#ifndef TINYMESH_SS_PIN
#define TINYMESH_SS_PIN      7
#endif

#ifndef TINYMESH_RST_PIN
#define TINYMESH_RST_PIN     1
#endif

#ifndef TINYMESH_DIO_PIN
#define TINYMESH_DIO_PIN     10
#endif

#define BLE_SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define BLE_CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"
#define BLE_PASSCODE_DEFAULT    671824

#ifndef TINYMESH_DEBUG_ENABLE
#define TINYMESH_DEBUG_ENABLE    true
#endif

#ifndef TINYMESH_DEBUG_LEVEL
#define TINYMESH_DEBUG_LEVEL     2
#endif

#ifndef TINYMESH_POWER_SAVING_DEFAULT
#define TINYMESH_POWER_SAVING_DEFAULT    false
#endif

#ifndef TINYMESH_INACTIVITY_TIMEOUT
#define TINYMESH_INACTIVITY_TIMEOUT      30000
#endif

#ifndef TINYMESH_SLEEP_DURATION
#define TINYMESH_SLEEP_DURATION          5000
#endif

#ifndef TINYMESH_MAX_NODES
#define TINYMESH_MAX_NODES 20
#endif

#ifndef TINYMESH_MAX_CHANNELS
#define TINYMESH_MAX_CHANNELS 10
#endif

#ifndef TINYMESH_DEFAULT_FREQUENCY
#define TINYMESH_DEFAULT_FREQUENCY 433E6
#endif

#ifndef TINYMESH_MAX_HOPS
#define TINYMESH_MAX_HOPS 3
#endif

#ifndef TINYMESH_DISCOVERY_INTERVAL
#define TINYMESH_DISCOVERY_INTERVAL 60000
#endif

#ifndef TINYMESH_NODE_TIMEOUT
#define TINYMESH_NODE_TIMEOUT 300000
#endif

#ifndef TINYMESH_POSITION_UPDATE_INTERVAL
#define TINYMESH_POSITION_UPDATE_INTERVAL 120000
#endif

#ifndef TINYMESH_ACK_TIMEOUT
#define TINYMESH_ACK_TIMEOUT 3000
#endif

#ifndef TINYMESH_RETRY_COUNT
#define TINYMESH_RETRY_COUNT 3
#endif

#define MSG_TYPE_DATA 0
#define MSG_TYPE_POSITION 1
#define MSG_TYPE_DISCOVERY 2
#define MSG_TYPE_ACK 3
#define MSG_TYPE_CHANNEL_DATA 4
#define MSG_TYPE_ADMIN 5

#define NODENUM_RESERVED 0xFFFFFFFF